// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rpc.proto

package ola.rpc;

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    REQUEST(0, 1),
    RESPONSE(1, 2),
    RESPONSE_CANCEL(2, 3),
    RESPONSE_FAILED(3, 4),
    RESPONSE_NOT_IMPLEMENTED(4, 5),
    DISCONNECT(5, 6),
    DESCRIPTOR_REQUEST(6, 7),
    DESCRIPTOR_RESPONSE(7, 8),
    REQUEST_CANCEL(8, 9),
    STREAM_REQUEST(9, 10),
    ;
    
    public static final int REQUEST_VALUE = 1;
    public static final int RESPONSE_VALUE = 2;
    public static final int RESPONSE_CANCEL_VALUE = 3;
    public static final int RESPONSE_FAILED_VALUE = 4;
    public static final int RESPONSE_NOT_IMPLEMENTED_VALUE = 5;
    public static final int DISCONNECT_VALUE = 6;
    public static final int DESCRIPTOR_REQUEST_VALUE = 7;
    public static final int DESCRIPTOR_RESPONSE_VALUE = 8;
    public static final int REQUEST_CANCEL_VALUE = 9;
    public static final int STREAM_REQUEST_VALUE = 10;
    
    
    public final int getNumber() { return value; }
    
    public static Type valueOf(int value) {
      switch (value) {
        case 1: return REQUEST;
        case 2: return RESPONSE;
        case 3: return RESPONSE_CANCEL;
        case 4: return RESPONSE_FAILED;
        case 5: return RESPONSE_NOT_IMPLEMENTED;
        case 6: return DISCONNECT;
        case 7: return DESCRIPTOR_REQUEST;
        case 8: return DESCRIPTOR_RESPONSE;
        case 9: return REQUEST_CANCEL;
        case 10: return STREAM_REQUEST;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ola.rpc.Rpc.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final Type[] VALUES = {
      REQUEST, RESPONSE, RESPONSE_CANCEL, RESPONSE_FAILED, RESPONSE_NOT_IMPLEMENTED, DISCONNECT, DESCRIPTOR_REQUEST, DESCRIPTOR_RESPONSE, REQUEST_CANCEL, STREAM_REQUEST, 
    };
    
    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private Type(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:ola.rpc.Type)
  }
  
  public interface RpcMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .ola.rpc.Type type = 1;
    boolean hasType();
    ola.rpc.Rpc.Type getType();
    
    // optional uint32 id = 2;
    boolean hasId();
    int getId();
    
    // optional string name = 3;
    boolean hasName();
    String getName();
    
    // optional bytes buffer = 4;
    boolean hasBuffer();
    com.google.protobuf.ByteString getBuffer();
  }
  public static final class RpcMessage extends
      com.google.protobuf.GeneratedMessage
      implements RpcMessageOrBuilder {
    // Use RpcMessage.newBuilder() to construct.
    private RpcMessage(Builder builder) {
      super(builder);
    }
    private RpcMessage(boolean noInit) {}
    
    private static final RpcMessage defaultInstance;
    public static RpcMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public RpcMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ola.rpc.Rpc.internal_static_ola_rpc_RpcMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ola.rpc.Rpc.internal_static_ola_rpc_RpcMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .ola.rpc.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private ola.rpc.Rpc.Type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public ola.rpc.Rpc.Type getType() {
      return type_;
    }
    
    // optional uint32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getId() {
      return id_;
    }
    
    // optional string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes buffer = 4;
    public static final int BUFFER_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString buffer_;
    public boolean hasBuffer() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getBuffer() {
      return buffer_;
    }
    
    private void initFields() {
      type_ = ola.rpc.Rpc.Type.REQUEST;
      id_ = 0;
      name_ = "";
      buffer_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, buffer_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, buffer_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ola.rpc.Rpc.RpcMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ola.rpc.Rpc.RpcMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ola.rpc.Rpc.RpcMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ola.rpc.Rpc.RpcMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ola.rpc.Rpc.RpcMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ola.rpc.Rpc.RpcMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ola.rpc.Rpc.RpcMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ola.rpc.Rpc.RpcMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ola.rpc.Rpc.RpcMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ola.rpc.Rpc.RpcMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ola.rpc.Rpc.RpcMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ola.rpc.Rpc.RpcMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ola.rpc.Rpc.internal_static_ola_rpc_RpcMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ola.rpc.Rpc.internal_static_ola_rpc_RpcMessage_fieldAccessorTable;
      }
      
      // Construct using ola.rpc.Rpc.RpcMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = ola.rpc.Rpc.Type.REQUEST;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        buffer_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ola.rpc.Rpc.RpcMessage.getDescriptor();
      }
      
      public ola.rpc.Rpc.RpcMessage getDefaultInstanceForType() {
        return ola.rpc.Rpc.RpcMessage.getDefaultInstance();
      }
      
      public ola.rpc.Rpc.RpcMessage build() {
        ola.rpc.Rpc.RpcMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ola.rpc.Rpc.RpcMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ola.rpc.Rpc.RpcMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ola.rpc.Rpc.RpcMessage buildPartial() {
        ola.rpc.Rpc.RpcMessage result = new ola.rpc.Rpc.RpcMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.buffer_ = buffer_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ola.rpc.Rpc.RpcMessage) {
          return mergeFrom((ola.rpc.Rpc.RpcMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ola.rpc.Rpc.RpcMessage other) {
        if (other == ola.rpc.Rpc.RpcMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasBuffer()) {
          setBuffer(other.getBuffer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              ola.rpc.Rpc.Type value = ola.rpc.Rpc.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              name_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              buffer_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .ola.rpc.Type type = 1;
      private ola.rpc.Rpc.Type type_ = ola.rpc.Rpc.Type.REQUEST;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public ola.rpc.Rpc.Type getType() {
        return type_;
      }
      public Builder setType(ola.rpc.Rpc.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = ola.rpc.Rpc.Type.REQUEST;
        onChanged();
        return this;
      }
      
      // optional uint32 id = 2;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // optional string name = 3;
      private Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
      }
      
      // optional bytes buffer = 4;
      private com.google.protobuf.ByteString buffer_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasBuffer() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getBuffer() {
        return buffer_;
      }
      public Builder setBuffer(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        buffer_ = value;
        onChanged();
        return this;
      }
      public Builder clearBuffer() {
        bitField0_ = (bitField0_ & ~0x00000008);
        buffer_ = getDefaultInstance().getBuffer();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ola.rpc.RpcMessage)
    }
    
    static {
      defaultInstance = new RpcMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ola.rpc.RpcMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ola_rpc_RpcMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ola_rpc_RpcMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tRpc.proto\022\007ola.rpc\"S\n\nRpcMessage\022\033\n\004ty" +
      "pe\030\001 \002(\0162\r.ola.rpc.Type\022\n\n\002id\030\002 \001(\r\022\014\n\004n" +
      "ame\030\003 \001(\t\022\016\n\006buffer\030\004 \001(\014*\322\001\n\004Type\022\013\n\007RE" +
      "QUEST\020\001\022\014\n\010RESPONSE\020\002\022\023\n\017RESPONSE_CANCEL" +
      "\020\003\022\023\n\017RESPONSE_FAILED\020\004\022\034\n\030RESPONSE_NOT_" +
      "IMPLEMENTED\020\005\022\016\n\nDISCONNECT\020\006\022\026\n\022DESCRIP" +
      "TOR_REQUEST\020\007\022\027\n\023DESCRIPTOR_RESPONSE\020\010\022\022" +
      "\n\016REQUEST_CANCEL\020\t\022\022\n\016STREAM_REQUEST\020\n"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ola_rpc_RpcMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ola_rpc_RpcMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ola_rpc_RpcMessage_descriptor,
              new java.lang.String[] { "Type", "Id", "Name", "Buffer", },
              ola.rpc.Rpc.RpcMessage.class,
              ola.rpc.Rpc.RpcMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
